version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=a
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=bookshop
    ports:
      - "1706:5432"

  emt-application:
    build: .
    container_name: emt-container
    depends_on:
      - postgres-db
    ports:
      - "2222:2222"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bookshop
      - SPRING_DATASOURCE_USERNAME=a
      - SPRING_DATASOURCE_PASSWORD=a
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect